CREATE TABLE IF NOT EXISTS yngc0der_oauth2server_auth_codes (
    ID VARCHAR(80) NOT NULL,
    IS_REVOKED TINYINT(1) NOT NULL,
    USER_ID INT NOT NULL,
    CLIENT_ID VARCHAR(80) NOT NULL,
    SCOPES TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS yngc0der_oauth2server_clients (
    ID VARCHAR(80) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    IS_CONFIDENTIAL TINYINT(1) NOT NULL,
    REDIRECT_URI VARCHAR(255) NOT NULL,
    SECRET VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS yngc0der_oauth2server_refresh_tokens (
    ID VARCHAR(80) NOT NULL,
    EXPIRE_DATE DATETIME NOT NULL,
    ACCESS_TOKEN_ID VARCHAR(80) NOT NULL,
    IS_REVOKED TINYINT(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS yngc0der_oauth2server_tokens (
    ID VARCHAR(80) NOT NULL,
    IS_REVOKED TINYINT(1) NOT NULL,
    USER_ID INT NOT NULL,
    CLIENT_ID VARCHAR(80) NOT NULL,
    SCOPES TEXT NOT NULL
);
